set(OTTO_VERSION 0.0.5)
list(APPEND CMAKE_MODULE_PATH ${CMAKE_CURRENT_LIST_DIR})
set(OTTO_TEMPLATE_DIR ${CMAKE_CURRENT_LIST_DIR}/templates)
set(OTTO_TOOLCHAIN_DIR ${CMAKE_CURRENT_LIST_DIR}/toolchains)

include(otto_set_toolchain)
